# -*- coding: utf-8 -*-
"""
/***************************************************************************
 YOLO-MOD Dialog
                                 
 QGIS plugin: YOLO-based detection of aircraft, airports, ships, helicopters, and storage tanks in satellite imagery.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-04-26
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Mateusz Strzelecki, Miraslau Farelnik, and Marcin Ciecholewski
        email                :  marcin.ciecholewski@pg.edu.pl

 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
from functools import partial

from qgis.core import QgsSettings
from qgis.PyQt import QtWidgets, uic
from qgis.PyQt.QtGui import QColor
from qgis.PyQt.QtWidgets import QColorDialog, QHBoxLayout, QLabel, QPushButton, QFileDialog

FORM_CLASS, _ = uic.loadUiType(os.path.join(os.path.dirname(__file__), "yolo_plugin_dialog_base.ui"))


class YOLOPluginDialog(QtWidgets.QDialog, FORM_CLASS):
    """Dialog UI for YOLO plugin settings and export options.

    This class wraps the generated UI form and provides helper methods to
    read user-configured options (model paths, colors, thresholds) used by
    the main plugin class.
    """
    def __init__(self, parent=None):
        super(YOLOPluginDialog, self).__init__(parent)
        self.setupUi(self)
        self.btn_detect_ok.clicked.connect(self.accept)
        self.btn_detect_cancel.clicked.connect(self.reject)
        self.btn_export_save.clicked.connect(self.accept)
        self.btn_export_cancel.clicked.connect(self.reject)
        self.btn_merge_run.clicked.connect(self.accept)
        self.btn_merge_cancel.clicked.connect(self.reject)
        self.btn_tiling_run.clicked.connect(self.accept)
        self.btn_tiling_cancel.clicked.connect(self.reject)
        self.btn_preview_run.clicked.connect(self.accept)
        self.btn_preview_cancel.clicked.connect(self.reject)
        self.spinBox_fill_transparency.setValue(50)
        self.lineEdit_model2.setEnabled(False)
        self.toolButton_model2.setEnabled(False)
        self.btn_tiling_run.setText("Preview && Start Tiling")
        self.checkBox_run_multiple.stateChanged.connect(
            lambda state: self.set_multiple_models_enabled(state == 2)
        )
        self.toolButton_model1.clicked.connect(self.select_model_path)
        self.toolButton_model2.clicked.connect(self.select_model_path2)
        self.toolButton_export_dir.clicked.connect(self.select_export_dir)
        self.toolButton_tiling_dir.clicked.connect(self.select_tiling_dir)
        self.toolButton_preview_img.clicked.connect(self.select_preview_img)
        self.toolButton_preview_txt.clicked.connect(self.select_preview_txt)
        self.radio_append_layer.toggled.connect(self.comboBox_target_layer.setEnabled)
        #self.display_class_names = ["plane", "bridge", "airport", "harbor", "vehicle", "ship"]
        self.default_colors = {
            "plane": "blue",
            "bridge": "orange",
            "airport": "yellow",
            "harbor": "red",
            "vehicle": "cyan",
            "ship": "magenta"
        }
        self.color_buttons = {}
        self.populate_color_pickers()
        self.checkBox_fill.stateChanged.connect(self.update_transparency_enabled)
        self.update_transparency_enabled()

    def _select_path(self, line_edit, title, is_dir=False, file_filter="", use_settings=True):
        """Generic helper for selecting a file or directory path."""
        settings = QgsSettings()
        last_dir = settings.value("YOLOPlugin/last_model_dir", os.path.expanduser("~")) if use_settings else ""
        
        if is_dir:
            path = QFileDialog.getExistingDirectory(self, title, last_dir)
        else:
            path, _ = QFileDialog.getOpenFileName(self, title, last_dir, file_filter)
        
        if path:
            line_edit.setText(path)
            if use_settings and not is_dir:
                settings.setValue("YOLOPlugin/last_model_dir", os.path.dirname(path))

    def populate_color_pickers(self):
        """Create color picker buttons for each object class.

        Each class gets outline and fill buttons that let the user choose
        colors used when rendering detection polygons.
        """
        for class_name, default_color in self.default_colors.items():
            layout = QHBoxLayout()
            label = QLabel(class_name)
            outline_btn = QPushButton()
            fill_btn = QPushButton()

            outline_btn.setStyleSheet(f"background-color: {default_color}")
            fill_btn.setStyleSheet(f"background-color: {default_color}")

            outline_btn.clicked.connect(partial(self.select_color, class_name, "outline"))
            fill_btn.clicked.connect(partial(self.select_color, class_name, "fill"))

            layout.addWidget(label)
            layout.addWidget(outline_btn)
            layout.addWidget(fill_btn)

            self.verticalLayout_colors.addLayout(layout)
            self.color_buttons[class_name] = {"outline": outline_btn, "fill": fill_btn}

    def select_export_dir(self):
        """Open a directory chooser and set the export directory field."""
        self._select_path(self.lineEdit_export_dir, "Select Export Directory", is_dir=True, use_settings=False)

    def select_tiling_dir(self):
        """Open a directory chooser and set the tiling export directory field."""
        self._select_path(self.lineEdit_tiling_dir, "Select Tiling Export Directory", is_dir=True, use_settings=False)

    def select_color(self, class_name, kind):
        """Show a QColorDialog and store the selected color for class rendering.

        The chosen color is stored as a hex string in the internal `color_buttons` map.
        """
        color = QColorDialog.getColor()
        if color.isValid():
            color_hex = color.name()
            self.color_buttons[class_name][kind].setStyleSheet(f"background-color: {color_hex}")
            self.color_buttons[class_name][f"{kind}_hex"] = color_hex

    def get_class_colors(self):
        """Return a mapping of class names to color hex values for outline and fill.

        Falls back to the configured defaults when the user did not choose a color.
        """
        colors = {}
        for name, default_color in self.default_colors.items():
            default_hex = QColor(default_color).name()
            btn_data = self.color_buttons[name]
            colors[name] = {
                "outline": btn_data.get("outline_hex", default_hex),
                "fill": btn_data.get("fill_hex", default_hex)
            }
        return colors

    def get_save_option(self):
        return "new" if self.radio_new_layer.isChecked() else "append"

    def get_target_layer_name(self):
        return self.comboBox_target_layer.currentText()

    def get_confidence_threshold(self):
        return self.spinBox_confidence.value()

    def get_fill_enabled(self):
        return self.checkBox_fill.isChecked()

    def get_fill_transparency(self):
        return self.spinBox_fill_transparency.value()

    def get_outline_transparency(self):
        return self.spinBox_outline_transparency.value()

    def update_transparency_enabled(self):
        self.spinBox_fill_transparency.setEnabled(self.checkBox_fill.isChecked())

    def select_model_path(self):
        """Open a file dialog to select the primary YOLO model file and remember its folder."""
        self._select_path(self.lineEdit_model1, "Select YOLO Model", file_filter="*.pt *.onnx")

    def select_model_path2(self):
        """Open a file dialog to select the secondary YOLO model file (optional)."""
        self._select_path(self.lineEdit_model2, "Select YOLO Model", file_filter="*.pt *.onnx")

    def set_multiple_models_enabled(self, enabled):
        """Enable or disable the secondary model UI controls based on checkbox state."""
        self.lineEdit_model2.setEnabled(enabled)
        self.toolButton_model2.setEnabled(enabled)

    def get_second_model_path(self):
        return self.lineEdit_model2.text()

    def get_run_multiple(self):
        return self.checkBox_run_multiple.isChecked()

    def get_merge_layers(self):
        return self.comboBox_merge_from.currentText(), self.comboBox_merge_to.currentText()

    def get_tiling_params(self):
        return {
            "width": self.spinBox_tile_width.value(),
            "height": self.spinBox_tile_height.value(),
            "dir": self.lineEdit_tiling_dir.text()
        }

    def set_canvas_resolution_display(self, width, height):
        self.label_canvas_res_value.setText(f"{width} x {height} px")

    def select_preview_img(self):
        self._select_path(self.lineEdit_preview_img, "Select Image", file_filter="Images (*.png *.jpg)", use_settings=False)

    def select_preview_txt(self):
        self._select_path(self.lineEdit_preview_txt, "Select YOLO Labels", file_filter="Text Files (*.txt)", use_settings=False)

    def get_preview_paths(self):
        return self.lineEdit_preview_img.text(), self.lineEdit_preview_txt.text()
