# -*- coding: utf-8 -*-
"""
/***************************************************************************
 YOLOPluginDialog
                                 A QGIS plugin
 Detect planes, airports, ships, helicopters and oil tankers from satellite imagery using a YOLO model.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-04-26
        git sha              : $Format:%H$
        copyright            : (C) 2025 by John doe
        email                : john.doe@email.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
from functools import partial

from qgis.core import QgsSettings
from qgis.PyQt import QtWidgets, uic
from qgis.PyQt.QtGui import QColor
from qgis.PyQt.QtWidgets import QColorDialog, QHBoxLayout, QLabel, QPushButton, QFileDialog

FORM_CLASS, _ = uic.loadUiType(os.path.join(os.path.dirname(__file__), "yolo_plugin_dialog_base.ui"))


class YOLOPluginDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        super(YOLOPluginDialog, self).__init__(parent)
        self.setupUi(self)
        self.btn_detect_ok.clicked.connect(self.accept)
        self.btn_detect_cancel.clicked.connect(self.reject)
        self.btn_export_save.clicked.connect(self.accept)
        self.btn_export_cancel.clicked.connect(self.reject)
        self.spinBox_fill_transparency.setValue(50)
        self.lineEdit_model2.setEnabled(False)
        self.toolButton_model2.setEnabled(False)
        self.checkBox_run_multiple.stateChanged.connect(
            lambda state: self.set_multiple_models_enabled(state == 2)
        )
        self.toolButton_model1.clicked.connect(self.select_model_path)
        self.toolButton_model2.clicked.connect(self.select_model_path2)
        self.toolButton_export_dir.clicked.connect(self.select_export_dir)
        self.radio_append_layer.toggled.connect(self.comboBox_target_layer.setEnabled)
        self.display_class_names = ["airport", "helicopter", "storage tank", "aircraft", "warship", "civil ship"]
        self.default_colors = {
            "airport": "blue",
            "helicopter": "orange",
            "aircraft": "yellow",
            "storage tank": "red",
            "warship": "cyan",
            "civil ship": "magenta"
        }
        self.color_buttons = {}
        self.populate_color_pickers()
        self.checkBox_fill.stateChanged.connect(self.update_transparency_enabled)
        self.update_transparency_enabled()

    def populate_color_pickers(self):
        for class_name in self.display_class_names:
            layout = QHBoxLayout()
            label = QLabel(class_name)
            outline_btn = QPushButton()
            fill_btn = QPushButton()

            outline_btn.setStyleSheet(f"background-color: {self.default_colors[class_name]}")
            fill_btn.setStyleSheet(f"background-color: {self.default_colors[class_name]}")

            outline_btn.clicked.connect(partial(self.select_color, class_name, "outline"))
            fill_btn.clicked.connect(partial(self.select_color, class_name, "fill"))

            layout.addWidget(label)
            layout.addWidget(outline_btn)
            layout.addWidget(fill_btn)

            self.verticalLayout_colors.addLayout(layout)
            self.color_buttons[class_name] = {"outline": outline_btn, "fill": fill_btn}

    def select_export_dir(self):
        directory = QFileDialog.getExistingDirectory(self, "Select Export Directory")
        if directory:
            self.lineEdit_export_dir.setText(directory)

    def select_color(self, class_name, kind):
        color = QColorDialog.getColor()
        if color.isValid():
            color_hex = color.name()
            self.color_buttons[class_name][kind].setStyleSheet(f"background-color: {color_hex}")
            self.color_buttons[class_name][f"{kind}_hex"] = color_hex

    def get_class_colors(self):
        colors = {}
        for class_name in self.display_class_names:
            default_hex = QColor(self.default_colors.get(class_name, "black")).name()
            colors[class_name] = {
                "outline": self.color_buttons[class_name].get("outline_hex", default_hex),
                "fill": self.color_buttons[class_name].get("fill_hex", default_hex)
            }
        return colors

    def get_save_option(self):
        return "new" if self.radio_new_layer.isChecked() else "append"

    def get_target_layer_name(self):
        return self.comboBox_target_layer.currentText()

    def get_confidence_threshold(self):
        return self.spinBox_confidence.value()

    def get_fill_enabled(self):
        return self.checkBox_fill.isChecked()

    def get_fill_transparency(self):
        return self.spinBox_fill_transparency.value()

    def get_outline_transparency(self):
        return self.spinBox_outline_transparency.value()

    def update_transparency_enabled(self):
        self.spinBox_fill_transparency.setEnabled(self.checkBox_fill.isChecked())

    def select_model_path(self):
        settings = QgsSettings()
        last_dir = settings.value("YOLOPlugin/last_model_dir", os.path.expanduser("~"))
        filename, _ = QFileDialog.getOpenFileName(self, "Select YOLO Model", last_dir, "*.pt *.onnx")
        if filename:
            self.lineEdit_model1.setText(filename)
            new_dir = os.path.dirname(filename)
            settings.setValue("YOLOPlugin/last_model_dir", new_dir)

    def select_model_path2(self):
        settings = QgsSettings()
        last_dir = settings.value("YOLOPlugin/last_model_dir", os.path.expanduser("~"))
        filename, _ = QFileDialog.getOpenFileName(self, "Select YOLO Model", last_dir, "*.pt *.onnx")
        if filename:
            self.lineEdit_model2.setText(filename)
            new_dir = os.path.dirname(filename)
            settings.setValue("YOLOPlugin/last_model_dir", new_dir)

    def set_multiple_models_enabled(self, enabled):
        self.lineEdit_model2.setEnabled(enabled)
        self.toolButton_model2.setEnabled(enabled)

    def get_second_model_path(self):
        return self.lineEdit_model2.text()

    def get_run_multiple(self):
        return self.checkBox_run_multiple.isChecked()
