# -*- coding: utf-8 -*-
"""
/***************************************************************************
 YOLO-MOD Dialog
                                 
 QGIS plugin: YOLO-based detection of aircraft, airports, ships, helicopters, and storage tanks in satellite imagery.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-04-26
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Mateusz Strzelecki, Miraslau Farelnik, and Marcin Ciecholewski
        email                :  marcin.ciecholewski@pg.edu.pl

 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
import random
from functools import partial

from qgis.core import QgsSettings
from qgis.PyQt import QtWidgets, uic
from qgis.PyQt.QtGui import QColor
from qgis.PyQt.QtWidgets import QColorDialog, QHBoxLayout, QLabel, QPushButton, QFileDialog

FORM_CLASS, _ = uic.loadUiType(os.path.join(os.path.dirname(__file__), "yolo_plugin_dialog_base.ui"))


class YOLOPluginDialog(QtWidgets.QDialog, FORM_CLASS):
    """Dialog UI for YOLO plugin settings and export options.

    This class wraps the generated UI form and provides helper methods to
    read user-configured options (model paths, colors, thresholds) used by
    the main plugin class.
    """
    def __init__(self, parent=None):
        super(YOLOPluginDialog, self).__init__(parent)
        self.setupUi(self)
        self.btn_detect_ok.clicked.connect(self.accept)
        self.btn_detect_cancel.clicked.connect(self.reject)
        self.btn_export_save.clicked.connect(self.accept)
        self.btn_export_cancel.clicked.connect(self.reject)

        self.btn_merge_run.clicked.connect(lambda: self.done(10))
        self.btn_delete_selected.clicked.connect(lambda: self.done(11))
        self.btn_edit_close.clicked.connect(self.reject)

        self.btn_tiling_run.clicked.connect(self.accept)
        self.btn_tiling_cancel.clicked.connect(self.reject)
        self.btn_preview_run.clicked.connect(self.accept)
        self.btn_preview_cancel.clicked.connect(self.reject)
        self.spinBox_fill_transparency.setValue(50)
        self.lineEdit_model2.setEnabled(False)
        self.toolButton_model2.setEnabled(False)
        self.btn_tiling_run.setText("Preview && Start Tiling")
        self.checkBox_run_multiple.stateChanged.connect(
            lambda state: self.set_multiple_models_enabled(state == 2)
        )
        self.toolButton_model1.clicked.connect(self.select_model_path)
        self.toolButton_model2.clicked.connect(self.select_model_path2)
        self.toolButton_custom_model.clicked.connect(self.select_custom_model_path)
        self.toolButton_export_dir.clicked.connect(self.select_export_dir)
        self.toolButton_tiling_dir.clicked.connect(self.select_tiling_dir)
        self.toolButton_preview_img.clicked.connect(self.select_preview_img)
        self.toolButton_preview_txt.clicked.connect(self.select_preview_txt)
        self.radio_append_layer.toggled.connect(self.comboBox_target_layer.setEnabled)
        self.display_class_names = ["airport", "helicopter", "storage tank", "aircraft", "warship", "civilian ship"]
        self.default_colors = {
            "airport": "blue",
            "helicopter": "orange",
            "aircraft": "yellow",
            "storage tank": "red",
            "warship": "cyan",
            "civilian ship": "magenta"
        }
        self.color_buttons_standard = {}
        self.color_buttons_custom = {}
        self.populate_standard_color_pickers()
        self.checkBox_fill.stateChanged.connect(self.update_transparency_enabled)
        self.update_transparency_enabled()
        self.lineEdit_custom_model.textChanged.connect(self.on_custom_model_path_changed)

    def on_custom_model_path_changed(self, path):
        """Analyze the custom model to extract class names."""
        if not path or not os.path.exists(path):
            return
        
        if path.lower().endswith(".pt"):
            try:
                from ultralytics import YOLO
                model = YOLO(path)
                if hasattr(model, 'names') and model.names:
                    class_names = list(model.names.values())
                    self.populate_custom_color_pickers(class_names)
            except Exception as e:
                print(f"Failed to load custom model classes: {e}")

    def populate_standard_color_pickers(self):
        self._populate_pickers(self.display_class_names, self.verticalLayout_colors_standard, self.color_buttons_standard)

    def populate_custom_color_pickers(self, class_names):
        while self.verticalLayout_colors_custom.count() > 0:
            item = self.verticalLayout_colors_custom.takeAt(0)
            if item.layout():
                while item.layout().count() > 0:
                    sub_item = item.layout().takeAt(0)
                    if sub_item.widget():
                        sub_item.widget().deleteLater()
                item.layout().deleteLater()
            elif item.widget():
                item.widget().deleteLater()
        
        self.color_buttons_custom = {}
        self._populate_pickers(class_names, self.verticalLayout_colors_custom, self.color_buttons_custom)

    def _populate_pickers(self, class_names, layout, storage):
        """Generic helper to create color pickers."""
        for class_name in class_names:
            h_layout = QHBoxLayout()
            label = QLabel(class_name)
            outline_btn = QPushButton()
            fill_btn = QPushButton()

            if class_name in self.default_colors:
                color = self.default_colors[class_name]
            else:
                color = QColor(random.randint(0, 255), random.randint(0, 255), random.randint(0, 255)).name()
                
            outline_btn.setStyleSheet(f"background-color: {color}")
            fill_btn.setStyleSheet(f"background-color: {color}")

            outline_btn.clicked.connect(partial(self.select_color_dynamic, class_name, "outline", storage))
            fill_btn.clicked.connect(partial(self.select_color_dynamic, class_name, "fill", storage))

            h_layout.addWidget(label)
            h_layout.addWidget(outline_btn)
            h_layout.addWidget(fill_btn)

            layout.addLayout(h_layout)
            storage[class_name] = {"outline": outline_btn, "fill": fill_btn, "outline_hex": color, "fill_hex": color}

    def select_color_dynamic(self, class_name, kind, storage):
        color = QColorDialog.getColor()
        if color.isValid():
            color_hex = color.name()
            storage[class_name][kind].setStyleSheet(f"background-color: {color_hex}")
            storage[class_name][f"{kind}_hex"] = color_hex

    def get_active_model_info(self):
        """Returns (is_custom, model_path, class_colors)"""
        is_custom = self.tabWidget_models.currentIndex() == 1
        if is_custom:
            return True, self.lineEdit_custom_model.text(), self.get_class_colors_from(self.color_buttons_custom)
        else:
            return False, self.lineEdit_model1.text(), self.get_class_colors_from(self.color_buttons_standard)

    def get_class_colors_from(self, storage):
        colors = {}
        for name, btn_data in storage.items():
            default = QColor(self.default_colors.get(name, "gray")).name()
            colors[name] = {
                "outline": btn_data.get("outline_hex", default),
                "fill": btn_data.get("fill_hex", default)
            }
        return colors

    def get_class_colors(self):
        _, _, colors = self.get_active_model_info()
        return colors

    def select_custom_model_path(self):
        self._select_path(self.lineEdit_custom_model, "Select Custom YOLO Model", file_filter="*.pt")

    def _select_path(self, line_edit, title, is_dir=False, file_filter="", use_settings=True):
        """Generic helper for selecting a file or directory path."""
        settings = QgsSettings()
        last_dir = settings.value("YOLOPlugin/last_model_dir", os.path.expanduser("~")) if use_settings else ""
        
        if is_dir:
            path = QFileDialog.getExistingDirectory(self, title, last_dir)
        else:
            path, _ = QFileDialog.getOpenFileName(self, title, last_dir, file_filter)
        
        if path:
            line_edit.setText(path)
            if use_settings and not is_dir:
                settings.setValue("YOLOPlugin/last_model_dir", os.path.dirname(path))

    def select_export_dir(self):
        """Open a directory chooser and set the export directory field."""
        self._select_path(self.lineEdit_export_dir, "Select Export Directory", is_dir=True, use_settings=False)

    def select_tiling_dir(self):
        """Open a directory chooser and set the tiling export directory field."""
        self._select_path(self.lineEdit_tiling_dir, "Select Tiling Export Directory", is_dir=True, use_settings=False)

    def get_save_option(self):
        return "new" if self.radio_new_layer.isChecked() else "append"

    def get_target_layer_name(self):
        return self.comboBox_target_layer.currentText()

    def get_confidence_threshold(self):
        return self.spinBox_confidence.value()

    def get_fill_enabled(self):
        return self.checkBox_fill.isChecked()

    def get_fill_transparency(self):
        return self.spinBox_fill_transparency.value()

    def get_outline_transparency(self):
        return self.spinBox_outline_transparency.value()

    def update_transparency_enabled(self):
        self.spinBox_fill_transparency.setEnabled(self.checkBox_fill.isChecked())

    def select_model_path(self):
        """Open a file dialog to select the primary YOLO model file and remember its folder."""
        self._select_path(self.lineEdit_model1, "Select YOLO Model", file_filter="*.pt *.onnx")

    def select_model_path2(self):
        """Open a file dialog to select the secondary YOLO model file (optional)."""
        self._select_path(self.lineEdit_model2, "Select YOLO Model", file_filter="*.pt *.onnx")

    def set_multiple_models_enabled(self, enabled):
        """Enable or disable the secondary model UI controls based on checkbox state."""
        self.lineEdit_model2.setEnabled(enabled)
        self.toolButton_model2.setEnabled(enabled)

    def get_second_model_path(self):
        return self.lineEdit_model2.text()

    def get_run_multiple(self):
        return self.checkBox_run_multiple.isChecked()

    def get_merge_layers(self):
        return self.comboBox_merge_from.currentText(), self.comboBox_merge_to.currentText()

    def set_selection_info(self, text, enabled=True):
        self.label_selection_info.setText(text)
        self.btn_delete_selected.setEnabled(enabled)

    def get_tiling_params(self):
        return {
            "width": self.spinBox_tile_width.value(),
            "height": self.spinBox_tile_height.value(),
            "dir": self.lineEdit_tiling_dir.text()
        }

    def set_canvas_resolution_display(self, width, height):
        self.label_canvas_res_value.setText(f"{width} x {height} px")

    def select_preview_img(self):
        self._select_path(self.lineEdit_preview_img, "Select Image", file_filter="Images (*.png *.jpg)", use_settings=False)

    def select_preview_txt(self):
        self._select_path(self.lineEdit_preview_txt, "Select YOLO Labels", file_filter="Text Files (*.txt)", use_settings=False)

    def get_preview_paths(self):
        return self.lineEdit_preview_img.text(), self.lineEdit_preview_txt.text()
